class HexEncoder(object):
    @staticmethod
    def encode(data: bytes) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> bytes: ...

class Base64Encoder(object):
    @staticmethod
    def encode(data: bytes) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> bytes: ...

class URLSafeBase64Encoder(object):
    @staticmethod
    def encode(data: bytes) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> bytes: ...
