@startuml
skinparam backgroundColor white
skinparam participantBackgroundColor #EEEBDC
skinparam noteBackgroundColor #EEE

Inge4->Inge6:/get_attributes?id_token
Inge6->Redis:get(id_token)
Redis-->Inge6:attributes
Inge6-->Inge4:attributes
@enduml