@startuml
title retrieve-ac-flow

skinparam backgroundColor white
skinparam participantBackgroundColor #EEEBDC
skinparam noteBackgroundColor #EEE

participant RD_BC
participant IdPx
participant App

App->MAX:/authorize?redirect_uri&client_id&code_challenge&...
MAX->Redis:store(randstate, {code, authorize_query_params})

alt SAML >4.4 specification

    MAX-->App:HTMLResponse(form: AuthnRequest + RelayState=randstate, onload(submit))
    App->IdPx:post(AuthnRequest, Relaystate)

else SAML 3.5 specification

    MAX-->App:RedirectResponse(/digid-authn-endpoint?SAMLRequest=XXX&RelayStat=XXX&Signature=XXX&SigAlg=XXX)
    App->IdPx:redirect(AuthnRequest, Relaystate)

end

note over App, IdPx:user does login
IdPx-->App:redirect(/acs?SAMLArt=artifact)
App->MAX:/acs?SAMLArt=artifact&RelayState=randstate

MAX<->Redis:get(randstate)

MAX->Redis:store(arti:code, artifact)
MAX-->App:/redirect_uri?code=code

note over App: Logged in, now: get accesstoken
App->MAX:/accesstoken.body[client_id, code=XXX, redirect_uri, code_verifier]
Redis<->MAX:get(cc_cm:code)
MAX->MAX:validate code_verifier

Redis<->MAX:get(arti:code)
MAX->RD_BC:/resolve?artifact
MAX<--RD_BC:resolved artifact?attributes
MAX->MAX:validate artifactResponse

MAX->Redis:store(h(token), attributes)

MAX-->App:JSONResponse(access_token)
App->App:remember[access_token]
@enduml
