@startuml
title tvs.cc.coroncheck.nl/authorize

skinparam backgroundColor white
skinparam participantBackgroundColor #EEEBDC
skinparam noteBackgroundColor #EEE

participant IDPx
participant App

App->Inge6:/authorize?redirect_uri_1
App<--Inge6:/redirect_uri_1?code=XXX

note over App, Inge6:client/app does login
App->Inge6:/accesstoken.body[client, code=XXX, redirect_uri_2]

Inge6->App:Redirect(/login-digid, set_cookie[token])
App->Inge6:/login-digid
Inge6->App:Redirect(/IDPx)

App->IDPx:redirect
note over App, IDPx:user does login
IDPx-->App:artifact
App->Inge6:redirect to /acs?(artifact)

Inge6->RD_BC:/resolve?artifact
Inge6<--RD_BC:resolved artifact?attributes

Inge6->Redis:store(get_cookie[token.id_token], attributes)
Inge6->App:/redirect_uri_2
@enduml