name: Notify RDObeheer on config-changes

on:
  push:
    branches: [ main ]
    paths: [ 'max.conf.example', 'clients.json.example' ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Diff configfiles
        run: git diff main~1:max.conf.example max.conf.example > max.conf.diff
      - name: Diff configfiles
        run: git diff main~1:clients.json.example clients.json.example > clients.json.diff
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.prolocation.net
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions ${{github.repository}}
          to: fyi@irealisatie.nl
          from: Github actions <${{secrets.MAIL_USERNAME}}>
          secure: false
          body: >
             Config change in ${{github.repository}}
          attachments: max.conf.diff,clients.json.diff
          ignore_cert: false
          convert_markdown: false
